services:
  api:
    build:
      context: ..
      dockerfile: serving_pipeline/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - churn_network

  ui:
    build:
      context: ..
      dockerfile: serving_pipeline/Dockerfile.ui
    environment:
      API_URL: http://api:8000/predict
      BATCH_URL: http://api:8000/batch
      DRIFT_URL: http://api:8000/monitor/drift?format=html
      DRIFT_JSON_URL: http://api:8000/monitor/drift?format=json
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - churn_network

networks:
  churn_network:
    driver: bridge
